name: nai
channels:
  - pytorch
  - defaults
dependencies:
  - git
  - python
  - pip>=20.3
  - cudatoolkit
  - pytorch>=1.11.0
  - torchvision>=0.12.0
  - numpy>=1.19.2
  - pip:
    - accelerate
    - lightning_lite
    - diffusers
    - opencv-python
    - imageio
    - pytorch-lightning
    - hivemind==1.1.2
    - ftfy
    - omegaconf==2.1.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers==4.24.0
    - bitsandbytes==0.35.4
    - torchmetrics==0.6.0
    - kornia==0.6