name: nd
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
    - albumentations==0.4.3
    - diffusers
    - opencv-python==4.1.2.30
    - pudb==2019.2
    - invisible-watermark
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - kornia==0.6
    - accelerate
    - lightning_lite
    - diffusers
    - pytorch-lightning==1.8.1
    - hivemind==1.1.2
    - ftfy
    - transformers>=4.24.0
    - bitsandbytes>=0.35.4
    - torchmetrics>=0.7.0