name: test-run

trainer:
  model_url: https://pub-2fdef7a2969f43289c42ac5ae3412fd4.r2.dev/animesfw.tgz
  model_path: "model"
  init_batch_size: 1
  resolution: 512
  center_crop: false
  gradient_checkpointing: false
  clip_skip: 2
  seed: 1138
  precision: fp32
  half_encoder: false
  use_ema: true
  use_hivemind: false
  use_xformers: false
  lr_scale: linear
  attention_slicing: false
  
checkpoint:
  monitor: 'epoch'
  dirpath: checkpoint
  filename: 'sample-nd-epoch{epoch:02d}-loss{train_loss:.2f}'
  auto_insert_metric_name: false
  every_n_epochs: 3
  save_top_k: 5
  mode: 'max'
  save_last: true

lightning:
  accelerator: gpu
  devices: -1
  auto_select_gpus: true
  # limit_train_batches: 100
  max_epochs: 20
  precision: 16
  log_every_n_steps: 1
  accumulate_grad_batches: 1
  gradient_clip_val: 0
  auto_scale_batch_size: false
  auto_lr_find: false

arb:
  enabled: true
  debug: false
  base_res: [512, 512]
  max_size: [768, 512]
  divisible: 64
  max_ar_error: 4
  min_dim: 256
  dim_limit: 1024

dataset:
  img_path: 
    - "https://pub-2fdef7a2969f43289c42ac5ae3412fd4.r2.dev/mmk.tgz"
  center_crop: false
  ucg: 0.0
  debug_arb: false
  num_workers: 3
  process_tags: true
  augment:
    enabled: false
    debug: false
    dropout: 0.5
    methods:
      adjust_brightness: 1.1
      adjust_contrast: 1.1
      rotate_with_crop: 10

scheduler:
  name: diffusers.DDIMScheduler
  params:
      beta_end: 0.012
      beta_schedule: "scaled_linear"
      beta_start: 0.00085
      clip_sample: false
      num_train_timesteps: 1000
      set_alpha_to_one: false
      steps_offset: 1
      trained_betas: null

optimizer:
  name: torch.optim.AdamW
  params:
    lr: 5e-6
    weight_decay: 1e-2
    eps: 1e-8

lr_scheduler:
  name: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  warmup: 
    enabled: false
    init_lr: 2e-8
    num_warmup: 50
    warmup_strategy: "cos"
  params:
    T_0: 10
    T_mult: 1
    eta_min: 7e-8
    last_epoch: -1

monitor:
  wandb_id: ""
  huggingface_repo: ""
  hf_auth_token: ""
  store_checkpoints: true

encoder:
  # Leave blank to load from model
  text: 
  vae: 